---

services:
  awesome-compose-web:
    image: afanozie/awesome-compose-web:latest
    container_name: awesome-compose-web
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.awesome-compose-web.rule=Host(`awesome-compose-web.duckdns.org`)"
      - "traefik.http.routers.awesome-compose-web.entrypoints=websecure"
      - "traefik.http.routers.awesome-compose-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.awesome-compose-web.loadbalancer.server.port=5000"

networks:
  traefik:
    external: true
