version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    restart: unless-stopped
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`gemsjenkins.duckdns.org`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls.certresolver=letsencrypt"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"

volumes:
  jenkins_home:

networks:
  traefik:
    external: true
