pipeline {
    agent any

    environment {
        IMAGE = 'afanozie/awesome-compose-web'
        TAG = "${env.BUILD_NUMBER}"
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '1'))
        disableConcurrentBuilds()
    }

    stages {
         stage('Clone Repository') {
            steps {
                sh 'rm -rf awesome-compose'
                sh 'git clone https://github.com/anoziefc/gems-task-test-repo.git'
            }
        }
        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: '840930c9-9610-4466-b21c-076ef150e8c5', usernameVariable: 'Username', passwordVariable: 'Password')]) {
                    sh 'echo $Password | docker login -u $Username --password-stdin'
                }
            }
        }
        stage('Docker Build') {
            steps {
                dir('gems-task-test-repo') {
                    sh """
                        docker build -t ${IMAGE}:${TAG} .
                        docker tag ${IMAGE}:${TAG} ${IMAGE}:latest
                    """
                }
            }
        }
        stage('Docker Push') {
            steps {
                sh """
                    docker push ${IMAGE}:${TAG}
                    docker push ${IMAGE}:latest
                """
            }
        }
        stage('Cleanup') {
            steps {
                sh 'docker system prune -af'
            }
        }  
    }

    post {
        always {
            sh 'docker logout || true'
        }
    }
}
